# Generated by Django 3.0.6 on 2020-05-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('aluno', models.CharField(max_length=100, verbose_name='Aluno')),
                ('universidade', models.CharField(blank=True, max_length=50, verbose_name='Universidade')),
                ('rg', models.CharField(blank=True, max_length=15, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=15, verbose_name='CPF')),
                ('curso', models.TextField(verbose_name='Curso')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('data', models.DateField(verbose_name='Data')),
                ('parceria', models.IntegerField(choices=[(1, 'ATENS'), (2, 'FLACSO'), (3, 'Prefeitura de Suzano')], verbose_name='Parceria')),
                ('slug', models.UUIDField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ('data', 'curso', 'aluno'),
            },
        ),
    ]
