# Generated by Django 3.0.6 on 2020-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='modalidade',
            field=models.IntegerField(choices=[(1, 'Atividade interativa'), (2, 'EAD'), (3, 'presencial')], default=1, verbose_name='Modalidade'),
            preserve_default=False,
        ),
    ]
