# Generated by Django 3.0.6 on 2020-07-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_certificado_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='parceria',
            field=models.IntegerField(choices=[(1, 'ATENS'), (4, 'ATENS - Dir. Rosário'), (2, 'FLACSO'), (3, 'Prefeitura de Suzano')], verbose_name='Parceria'),
        ),
    ]
