# Generated by Django 3.0.8 on 2020-07-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0003_auto_20200714_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='carga_horaria',
            field=models.CharField(max_length=15, verbose_name='Carga horária'),
        ),
    ]
